### ISSUE TITLE
More inclusive imagery

### ISSUE THREAD

**Issue by amcaplan** [rails/homepage#102]
Let me start out by saying: I love the new site design, and all the images in https://github.com/rails/homepage/tree/57498c170f5ad26b552c22081403f6dc4cfe6036/images are so much friendlier than they were previously, and will make Rails more appealing and approachable to new programmers.

I'd like to suggest a further improvement.  Currently, there is pretty good variety in terms of gender and age.  However, there is 1 non-white person (specifically, the hand of a person of color in https://github.com/rails/homepage/blob/57498c170f5ad26b552c22081403f6dc4cfe6036/images/conduct.png) in all the images I've been able to find.  There's also some irony in the globe image (https://github.com/rails/rails/blob/3278bca8771bacbc5b9574ee202f153651178142/guides/assets/images/getting_started/rails_welcome.png) which decorates the beautiful new welcome page having a bunch of people whom I wouldn't be surprised to see living on the same block in Palo Alto representing Rails around the world.  It's not exactly a cultural cornucopia.

So, maybe we could take the original assets and look for ways to modify them to represent more of the full picture of the Rails community, and/or what we'd like it to look like.  That could mean different skin colors (it's admittedly hard to know what was meant when the drawings are more outliney, but they already have lots of splashes of color so may as well do that with skin color too), having garments more representative of world cultures (hijab or Sikh turban, perhaps, for a start?), maybe a wheelchair or a cane or a small hearing aid, or a seeing eye dog (there's already a dog in there!), or any other element of diverse and inclusive communities with a visible component.  (Feel free to add more dimensions in the comments, people!)

I suspect it would mean a lot to developers (and would-be developers!) to see that this is a community that isn't just welcoming to all skill levels and genders, but to people of all backgrounds and cultures, rooted in mutual respect and a [big tent philosophy](http://rubyonrails.org/doctrine/#big-tent).  Having just come from my fourth RailsConf, I've experienced this already in the community, and I think it would be just fantastic if our imagery reflected that as well.

So: How do we make this happen?

**Comment by dhh** [comment]
Agree with this and so does @asianmack who did the original artwork. He has updated the main welcome image that's used for new apps and we'll be looking at the rest of the images too 👌

https://github.com/rails/rails/pull/32735

**Comment by amcaplan** [comment]
Woot!  Love the new look! 🎉 Can't wait to see the rest of the series!
