### ISSUE TITLE
Insecure connection on rubyonrails.org and *.rubyonrails.org sites not responding 

### ISSUE THREAD

**Issue by rafaelgonzalez** [rails/homepage#105]
Hi everyone.

Just noticed that some rubyonrails.org subdomains are not responding:
- https://api.rubyonrails.org
- https://edgeguides.rubyonrails.org
- https://contributors.rubyonrails.org

I'm not sure if this is an issue across all subdomains (I don't know how many there are), or just these few that I know of.

Interestingly, https://rubyonrails.org does respond but with and "Insecure connection" warning on Firefox:

![screen shot 2018-05-08 at 10 22 22 am](https://user-images.githubusercontent.com/456921/39731238-ce9462b8-52a9-11e8-90de-dc27c5f55066.png)

I'm logging these under the same issue as I assume it's all related (essentially "sites are down") but happy to create two separate issues if more convenient. I'm also aware this is not a code-related issue so here might not be the most appropriate place to log the issues (let me know where if that's the case!)

Cheers

**Comment by dhh** [comment]
We did update DNS records today. Working with Rafael to get this sorted. Thanks for reporting!

**Comment by dhh** [comment]
We’ve fixed the SSL warning on the riot domain 👍. The subdomains never supported https and still don’t. But we will try to get that working in the future. Thanks again for reporting.
