### ISSUE TITLE
5.0 missing from Severe Security Issues?

### ISSUE THREAD

**Issue by jjb** [rails/homepage#108]
here: http://guides.rubyonrails.org/maintenance_policy.html#severe-security-issues

> Currently included series: 5.2.Z, 5.1.Z, 4.2.Z

Is 5.0.Z missing? Or is that some sort of exception for some reason?

**Comment by rafaelfranca** [comment]
Please see the guides source code. 5.0 is covered there. The documentation will update with a new release. When in doubt looks the edge guides http://edgeguides.rubyonrails.org/maintenance_policy.html
