### ISSUE TITLE
guides.rubyonrails.com is down

### ISSUE THREAD

**Issue by ricardograca** [rails/homepage#125]
Not sure if this is the right place, but I couldn't find any repository specific to `guides`. It appears that guides.rubyonrails.com has been down for over 2 days now according to https://www.isitdownrightnow.com/guides.rubyonrails.org.html.

I also confirm that it's not accessible. Sometimes the main page shows up, but it seems to be from cache as refreshing or clicking any link will show an error saying that the connection was terminated.

**Comment by kaspth** [comment]
Thanks for notifying us! cc @fxn do you know what's up?

**Comment by fxn** [comment]
I have restarted NGINX and it is up now.

This never happened before, NGINX was logging

```
worker_connections are not enough
```

like crazy.

**Comment by kaspth** [comment]
Thanks @fxn 🙏
