### ISSUE TITLE
Smaller image files

### ISSUE THREAD

**Issue by connorshea** [rails/homepage#13]
I'm admittedly not sure how reasonable this would be, but I figured I'd suggest it regardless. If you have the images in SVG format, it'd be preferable to use those for the site (that is, if they're any smaller than the PNG versions). Assuming the images are raster, would it be possible to losslessly compress the PNG files?

Right now the page is 1.1MB, which is pretty heavy for a static site. The images make up ~430KB of that. The images are absolutely beautiful, and I definitely don't want you to change them from an artistic point-of-view, but I would like them to bear a lighter load if it's at all possible.

@asianmack I assume you'd be the best to ask about this?

**Comment by nateberkopec** [comment]
The background is solid #FFF, so JPEG with a decent quality setting might also be appropriate.

**Comment by asianmack** [comment]
@connorshea @nateberkopec Agree. I can crunch these down more using JPEG. They won't have the transparency if people wanna remix them (for whatever reason). Lemme see what I can do.

**Comment by asianmack** [comment]
@connorshea @nateberkopec I crunched the images down by ~50% still using PNG but 8-bit.

**Comment by connorshea** [comment]
Awesome, thanks!
