### ISSUE TITLE
All trailing slashes are broken

### ISSUE THREAD

**Issue by sgrif** [rails/homepage#16]
We have a significant number of links both in old blog posts, and in the main repo, which link to a URL with a trailing slash. These now 404 (including our links to the CoC, which we probably want to keep alive).

The easiest solution would be to use a tool like Jekyll or Middleman, which handle it for us.

**Comment by maclover7** [comment]
Will take a stab at converting site to Middleman.

**Comment by jyunderwood** [comment]
@sgrif PR #22 adds trailing slashes to pages with jekyll.
