### ISSUE TITLE
Add Netlify previews for Pull Requests

### ISSUE THREAD

**Issue by MikeRogers0** [rails/homepage#164]
👋 I'd really like to start contributing to Rails more & I think the place I'd be most effective is improve the main websites performance ( [the performance could be a little better](https://lighthouse-dot-webdotdevsite.appspot.com//lh/html?url=https%3A%2F%2Frubyonrails.org%2F) ) & other bits.

The thing I'd want to start with that'll make contributing & reviewing easier, is adding preview environments for pull requests, I done something similar in https://github.com/zzak/sdoc/issues/162 where Netlify would spin up a temporary environment so we could see the change by clicking a link.

Would this be something you'd like (I'm super happy to make a PR to add any required files)? If possible I'd love to do the same to https://guides.rubyonrails.org/ :)

CC: @guilleiguaran

**Comment by guilleiguaran** [comment]
Hello @MikeRogers0, as you can see this repo isn't really very active, it gets updated only sporadically (and mainly by the Rails team itself) and there aren't many open pull requests looking to update it so I believe that it won't benefit much from previews.

On the other side, the Rails Guides are updated more frequently and need a lot of attention right now so I would prefer to add the previous for the Rails Guides instead, can we move this discussion to Rails? or even better can you create a super-minimal PR draft so it can be discussed? (creating this as  an issue in Rails probably will be considered a feature request and closed)

**Comment by MikeRogers0** [comment]
> On the other side, the Rails Guides are updated more frequently and need a lot of attention right now so I would prefer to add the previous for the Rails Guides instead, can we move this discussion to Rails? or even better can you create a super-minimal PR draft so it can be discussed? (creating this as an issue in Rails probably will be considered a feature request and closed)

Oh that sounds really cool! I've been meaning to post on the forum to gauge interest, but I'll cross post to https://github.com/rails/rails-docs-server/issues when I do :) 

I'm going to close this issue off in the interim :)

**Comment by MikeRogers0** [comment]
@guilleiguaran https://discuss.rubyonrails.org/t/move-guides-rubyonrails-org-to-be-behind-a-cdn/78657 - Posted btw :)
