### ISSUE TITLE
HTTPS

### ISSUE THREAD

**Issue by connorshea** [rails/homepage#37]
Adding HTTPS to the Rails website should be a no-brainer, seeing as [Release blog posts include checksums](http://weblog.rubyonrails.org/2016/1/25/Rails-5-0-0-beta1-1-4-2-5-1-4-1-14-1-3-2-22-1-and-rails-html-sanitizer-1-0-3-have-been-released/). If provided over HTTP rather than HTTPS, they're kind of pointless, as an attacker would be significantly more capable of modifying the page contents.

Would strongly recommend using HTTPS here, since it's a static site [Let's Encrypt](https://letsencrypt.org/) should work well, possibly even easier with the [acme-tiny](https://github.com/diafygi/acme-tiny) utility.

**Comment by dhh** [comment]
👍

**Comment by rafaelfranca** [comment]
GitHub pages, that is what we use for publishing our website, doesn't support HTTPS. Without moving this site to a different infrastructure or putting a CDN in front of it would be impossible to implement HTTPS. You can find the same checksums in the rubygems page (which uses HTTPS) so you can double check if there was any modification in the content using it.

I'm not sure if it is worth to use HTTPS in the website and blog until we have support for that in GitHub pages.

**Comment by AnthonySuper** [comment]
Well, you can just toss [Cloudflare](https://www.benburwell.com/posts/configuring-cloudflare-universal-ssl/) in front of it, which is probably a good idea anyway.

**Comment by rafaelfranca** [comment]
> Well, you can just toss Cloudflare in front of it, which is probably a good idea anyway.

Yes, that is exactly what I said with "putting a CDN in front of it". Having cloudflare still don't solve this issue because the connection between Cloudflare and GitHub pages will be unencrypted and an attacker would be able to modify the pages content there too

**Comment by schmijos** [comment]
GitHub pages **allows** *HTTPS* like that: `https://example.github.io`.

Even though you've to trust cloudflare in proxying the connection, I believe it's still the better solution than no *HTTPS*. What is more trustful in your eyes? Cloudflare or any WLAN accesspoint or *ISP* your visitors are using?

**Comment by AnthonySuper** [comment]
@rafaelfranca I still think it's valuable, as it prevents bad actors from snooping into user traffic.

The only way to have all the benefits of SSL is to host it on something besides Github pages, which I think might be a good idea anyway. I don't know much about hosting static sites, but, in all honesty, it doesn't sound too hard to just throw up an EC2 instance with NGINX and LetsEncrypt.

**Comment by 10by10pixel** [comment]
@AnthonySuper I know this issue is old but I'm putting my 2 cents in. But Github Pages is free and EC2 is not. Probably the only viable solution without a budget increase is Cloudflare but that'll mainly slow down GH Pages in my experience.

**Comment by connorshea** [comment]
They could always mirror this repository onto GitLab and use GitLab Pages with Let's Encrypt.

**Comment by jeremy** [comment]
We could host it ourselves again, but we moved to GH pages to get out of that business.

Odds are we can be patient a while and GitHub will support TLS sooner than later 😙

**Comment by 10by10pixel** [comment]
@jeremy That's prolly best course of action. I'm surprised they don't support it already.

**Comment by connorshea** [comment]
@jeremy You can use https://gitlab.com w/ Pages for free: https://pages.gitlab.io/

GitLab Pages is just like GitHub Pages, but with TLS :) I can understand not wanting to move off GitHub, but you can mirror the homepage repo and have commits synced between the two every hour. You can also trigger a manual sync if you want to get a change out ASAP.

Worth considering, but again, I can definitely understand the convenience of GH Pages.

Disclosure: GitLab employee :P

**Comment by jeremy** [comment]
Super cool, @connorshea! Thanks for sharing.

I see this as a nice-to-have at this point, outweighed by the value we got from consolidating our setup. Happy to wait weeks, months, to see if GitHub steps it up 😊

**Comment by twe4ked** [comment]
The first result in Google is pointing to the HTTPS URL which currently has a certificate error:

![screen shot 2017-03-17 at 1 26 11 pm](https://cloud.githubusercontent.com/assets/71970/24026464/73c4bf54-0b15-11e7-895a-94757c535a82.png)
![screen shot 2017-03-17 at 1 27 10 pm](https://cloud.githubusercontent.com/assets/71970/24026467/75a091ea-0b15-11e7-83ca-542ef68cf99b.png)

**Comment by 10by10pixel** [comment]
@twe4ked That's because the certificate is the one Github provided for `rails.github.io` which makes it invalid for `rubyonrails.org` the only solutions to that problem are the ones we've discussed earlier in the thread.

**Comment by dhh** [comment]
For now, we should have an option of providing a canonical metatag URL
that's just the HTTP version. Can someone take a look at that?

**Comment by 10by10pixel** [comment]
@dhh It already is

![<link rel="canonical" href="http://rubyonrails.org/" />
<meta property="og:url" content="http://rubyonrails.org/" />](https://cloud.githubusercontent.com/assets/5394990/24046329/967f581e-0af8-11e7-9a25-3d389cfb9f5c.png)

**Comment by 10by10pixel** [comment]
@dhh It already is

![<link rel="canonical" href="http://rubyonrails.org/" /><meta property="og:url" content="http://rubyonrails.org/" />](https://cloud.githubusercontent.com/assets/5394990/24046329/967f581e-0af8-11e7-9a25-3d389cfb9f5c.png)

**Comment by dhh** [comment]
Gotcha. So we're waiting for Google to pick that up?

**Comment by 10by10pixel** [comment]
Well best guess they're detecting that we have the certificate without seeing that it's invalid...

**Comment by eileencodes** [comment]
@dhh I beleive the Canonical tag was added after we found that google was picking https to index over http. If we (Rails) have google webmaster tools (or search console I think it's called now) we can force a re-crawl of the Rails site. If we don't we can add it easily enough and force a re-crawl.

**Comment by dhh** [comment]
I don't think we have the webmaster tools. I don't remember ever using
them. Please do take a swing at it!

**Comment by eileencodes** [comment]
Set rubyonrails.org up with google webmaster tools, submitted the sitemap, and requested a re-indexing from google. Hopefully that clears things up in 24 hours or so.

**Comment by GeorgeDewar** [comment]
How strange. Searching Google for "rails" gives me an http link which works, but "ruby on rails" gives an https link to the same page...

I would (like others) strongly encourage moving to https in any case. Even if there's not a compelling need, rails should be setting a good example in this regard - also, search engines and browsers are more and more favouring https.

**Comment by olivierlacan** [comment]
@eileencodes @dhh Someone should check the https://github.com/rails/homepage/settings since I noticed that GitHub has been trialing Let's Encrypt support for GitHub Pages sites. 

I just turned it on for keepachangelog.com last night and it was a breeze: 
![image](https://user-images.githubusercontent.com/65950/37298543-f8d4e4ec-25f6-11e8-9e6a-5b2a909cbe57.png)

![image](https://user-images.githubusercontent.com/65950/37298565-06c683ee-25f7-11e8-8dd1-9280a144076e.png)

It would be a really good thing if rubyonrails.org could be served through HTTPS.

**Comment by rafaelfranca** [comment]
From the setting page: "Unavailable for your site because you have a custom domain configured (rubyonrails.org)"

**Comment by olivierlacan** [comment]
Maybe @eileencodes can put in a good word with the team at GitHub responsible for this because Keep a Changelog definitely has the [same custom domain settings](https://github.com/olivierlacan/keep-a-changelog/blob/gh-pages/CNAME).

https://help.github.com/articles/securing-your-github-pages-site-with-https/ says: 
>  HTTPS is not supported for GitHub Pages using custom domains.

But clearly it's not true in all cases anymore.

**Comment by esparta** [comment]
Apparently is not a 'production ready' feature, still on testing phase, and not officially supported:
https://gist.github.com/coolaj86/e07d42f5961c68fc1fc8#gistcomment-2370070

>    Hi ligi,
    As you've discovered, some GitHub Pages sites have been issued SSL certificates from Let's Encrypt, enabling HTTPS for your custom domain. This isn't officially supported yet and it's not possible for you to enable and enforce it on your sites at this time.
   We know how important secure browsing is for our users, but we don't have anything official to announce at this time. If and when this feature is officially released, we will announce it on our blog:
    https://github.com/blog
>  Let us know if you have other questions!

> Thanks,
 Thomas
 GitHub Support

**Comment by paulRbr** [comment]
https://blog.github.com/2018-05-01-github-pages-custom-domains-https/

:point_up: this is good news from Github. Any chance to enable it for rubyonrails.org? Thanks!

**Comment by rafaelfranca** [comment]
@paulRbr 

From the setting page: "Unavailable for your site because you have a custom domain configured (rubyonrails.org)"

**Comment by 10by10pixel** [comment]
> Once your updated DNS records have propagated, and you’ve confirmed that your site loads correctly over HTTPS, you can optionally “Enforce HTTPS” for your domain in your repository’s settings, ensuring users who request your site over HTTP are upgraded to HTTPS.

**Comment by rafaelfranca** [comment]
https://rubyonrails.org/
