### ISSUE TITLE
Project Links from rails.gemspec and Rubygems lead to Nginx placeholder page

### ISSUE THREAD

**Issue by snkashis** [rails/homepage#46]
The url(**http://www.rubyonrails.org/**) listed on https://rubygems.org/gems/rails and https://github.com/rails/rails/blob/master/rails.gemspec#L17 currently lead me to the default "Welcome to nginx!" page. Instead of changing these urls to **http://rubyonrails.org/**  across these places(and the many others), shouldn't the redirect + server_name directive be properly configured?

> If you see this page, the nginx web server is successfully installed and working. Further configuration is required.
> 
> For online documentation and support please refer to nginx.org.
> Commercial support is available at nginx.com.
> 
> Thank you for using nginx.

**Comment by rafaelfranca** [comment]
We are working on it right now.

**Comment by rafaelfranca** [comment]
Done. Thank you for reporting.

**Comment by snkashis** [comment]
No problem.
